### ISSUE TITLE
ValidLabel Error

### ISSUE THREAD

**Issue by alimsvn** [martijneppenga/MaskRCNN#1]
Hi,
First I thank you for your great work.
When I wanted to test Mask R-CNN on the Shape dataSet (the example in Matterport for training our own dataset ) with your new edition of mrcnn, an error occurred:
AttributeError: 'ShapesConfig' object has no attribute 'ValidLabels'.

I also encountered the same error when used your new edition with my own dataset:
AttributeError: 'LBoundaryConfig' object has no attribute 'ValidLabels'.
Could you please instruct me on how to solve the problem?
Regards.

**Comment by martijneppenga** [comment]
Hi,

The ValidLablels is an attribute which should had been removed. It was used in a custom data generator. (Line 12     _self.ValidLabels = config.ValidLabels_  from _DataGenerator.py_   must be deleted)

I would recommend you to use the https://github.com/martijneppenga/Mask_RCNN repository, If you want to use the upgraded version to Tensorflow 2.1.0 of Maskrcnn of matterport. It contains the exact same python code, but it is a forked repository of matterports repository (which is useful for legacy) instead of a copied one.

I have removed the attribute ValidLabels in the forked repository (https://github.com/martijneppenga/Mask_RCNN). This should solve the error. In order for it to work you must run the setup.py script again.

**Comment by alimsvn** [comment]
> 
> 
> Hi,
> 
> The ValidLablels is an attribute which should had been removed. It was used in a custom data generator. (Line 12 _self.ValidLabels = config.ValidLabels_ from _DataGenerator.py_ must be deleted)
> 
> I would recommend you to use the https://github.com/martijneppenga/Mask_RCNN repository, If you want to use the upgraded version to Tensorflow 2.1.0 of Maskrcnn of matterport. It contains the exact same python code, but it is a forked repository of matterports repository (which is useful for legacy) instead of a copied one.
> 
> I have removed the attribute ValidLabels in the forked repository (https://github.com/martijneppenga/Mask_RCNN). This should solve the error. In order for it to work you must run the setup.py script again.

Thank you very much. It worked for me.
